### ISSUE TITLE
Error at "rails g i18n_backend_database" (Rails 3.1)

### ISSUE THREAD

**Issue by no-z** [dylanz/i18n_backend_database#12]
terminal output:

```
rails g i18n_backend_database
$HOME/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.3/lib/active_record/base.rb:1088:in `method_missing': undefined method `named_scope' for #<Class:0xa050d5c> (NoMethodError)ax
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/i18n_backend_database-0.0.1/lib/models/locale.rb:6:in `<class:Locale>'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/i18n_backend_database-0.0.1/lib/models/locale.rb:1:in `<top (required)>'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in `require'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in `block in require'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:223:in `block in load_dependency'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:640:in `new_constants_in'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:223:in `load_dependency'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in `require'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/i18n_backend_database-0.0.1/lib/i18n_backend_database.rb:1:in `<top (required)>'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.21/lib/bundler/runtime.rb:68:in `require'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.21/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.21/lib/bundler/runtime.rb:66:in `each'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.21/lib/bundler/runtime.rb:66:in `block in require'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.21/lib/bundler/runtime.rb:55:in `each'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.21/lib/bundler/runtime.rb:55:in `require'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.21/lib/bundler.rb:122:in `require'
  from /media/PORT/work/couture/config/application.rb:13:in `<top (required)>'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.3/lib/rails/commands.rb:21:in `require'
  from $HOME/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.3/lib/rails/commands.rb:21:in `<top (required)>'
  from script/rails:6:in `require'
  from script/rails:6:in `<main>'
```

**Comment by hassanrehman** [comment]
same issue ..  anyone watching this?
